name: 'Deploy to FutureNet-Telecom-Solutions-Inc repository main branch'

on:
  workflow_run:
    workflows: ['Build, Test, Deploy GitHub Pages']
    types:
      - completed
    branches:
      - 'main'

permissions:
  contents: write  # For GITHUB_TOKEN, though PAT overrides this

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          ref: github-pages

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Debug authentication
        run: |
          echo "Pushing as: ${{ secrets.USER_NAME }}"
          echo "Target: https://${{ secrets.USER_NAME }}:****@github.com/${{ secrets.USER_NAME }}/FutureNet-Telecom-Solutions-Inc.git"
          git remote add target https://${{ secrets.USER_NAME }}:${{ secrets.PAT }}@github.com/${{ secrets.USER_NAME }}/FutureNet-Telecom-Solutions-Inc.git
          git remote -v

      - name: Prepare docs directory and push to target repository
        run: |
          git fetch target main
          git checkout -b main target/main || git checkout main
          mkdir -p docs
          rm -rf docs/*
          find . -maxdepth 1 -not -name "." -not -name ".." -not -name ".git" -not -name "docs" -exec mv {} docs/ \;
          git add docs/
          git commit -m "Deploy contents to docs directory" || echo "No changes to commit"
          git push -f target main
        env:
          PAT: ${{ secrets.PAT }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
